logging:
  level:
    io.adrieldg: DEBUG

global:
  apiUrl: http://localhost:8081/

server:
  port: 8080

oauth2:
  clientId: chainofmemories-client
  clientSecret: keyblade
  accessTokenUri: oauth/token
  grantType: password
  scope: read,write,trust