logging:
  level:
    io.adrieldg: warn
global:
  apiUrl: ${API_URL}
server:
  port: 8080
oauth2:
  clientId: chainofmemories-client
  clientSecret: keyblade
  accessTokenUri: oauth/token
  grantType: password
  scope: read,write,trust
