server:
  port: 8080

security:
  oauth2:
      client:
          clientId: chainofmemories-client
          clientSecret: keyblade
          accessTokenUri: http://localhost:8081/oauth/token
          grantType: password
          client-authentication-scheme: header
  basic:
    enabled: false

global:
  api-url: http://localhost:8081/